In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('D:/Project/AI That Explains Medical Images Like a Doctor/Another way/Dataset/stage_2_train_labels.csv')

In [4]:
df2 = pd.read_csv('D:\Project\AI That Explains Medical Images Like a Doctor\Another way\Dataset\stage_2_detailed_class_info.csv')

In [5]:
df.head()

                              patientId      x      y  width  height  Target
0  0004cfab-14fd-4e49-80ba-63a80b6bddd6    NaN    NaN    NaN     NaN       0
1  00313ee0-9eaa-42f4-b0ab-c148ed3241cd    NaN    NaN    NaN     NaN       0
2  00322d4d-1c29-4943-afc9-b6754be640eb    NaN    NaN    NaN     NaN       0
3  003d8fa0-6bf1-40ed-b54c-ac657f8495c5    NaN    NaN    NaN     NaN       0
4  00436515-870c-4b36-a041-de91049b9ab4  264.0  152.0  213.0   379.0       1

In [24]:
df['patientId'][0]

'0004cfab-14fd-4e49-80ba-63a80b6bddd6'

In [6]:
df2.head()

                              patientId                         class
0  0004cfab-14fd-4e49-80ba-63a80b6bddd6  No Lung Opacity / Not Normal
1  00313ee0-9eaa-42f4-b0ab-c148ed3241cd  No Lung Opacity / Not Normal
2  00322d4d-1c29-4943-afc9-b6754be640eb  No Lung Opacity / Not Normal
3  003d8fa0-6bf1-40ed-b54c-ac657f8495c5                        Normal
4  00436515-870c-4b36-a041-de91049b9ab4                  Lung Opacity

In [25]:
df2[df2['class'] == 'No Lung Opacity / Not Normal'] = 'No Lung Opacity'

In [21]:
print(df.shape)
print(df2.shape)

(30227, 6)
(30227, 2)

In [18]:
df2['class'].unique()

array(['No Lung Opacity / Not Normal', 'Normal', 'Lung Opacity'],
      dtype=object)

In [14]:
df['Target'].value_counts()

Target
0    20672
1     9555
Name: count, dtype: int64

In [16]:
df2[(df2['patientId'] == df['patientId']) & df['Target'] == 1]['class'].value_counts()

class
Lung Opacity    9555
Name: count, dtype: int64

In [7]:
df2['class'].value_counts()

class
No Lung Opacity / Not Normal    11821
Lung Opacity                     9555
Normal                           8851
Name: count, dtype: int64

In [28]:
import os
import pandas as pd
import pydicom
import numpy as np
import cv2

# df and df2 already loaded
# df['patient_id']
# df2['class']

dicom_dir = r"D:\Project\AI That Explains Medical Images Like a Doctor\Another way\Dataset\stage_2_train_images"
output_root = r"D:\Project\AI That Explains Medical Images Like a Doctor\Another way\Dataset\images"

os.makedirs(output_root, exist_ok=True)

i=0
for idx in range(len(df)):
    patient_id = str(df.loc[idx, 'patientId'])
    class_name = str(df2.loc[idx, 'class'])

    print(f"Processing {i+1}/{len(df)}: {patient_id} -> {class_name}")
    i += 1
    dicom_path = os.path.join(dicom_dir, patient_id + ".dcm")

    # Skip if DICOM not found
    if not os.path.exists(dicom_path):
        print(f"❌ Missing: {patient_id}.dcm")
        continue

    # Create class folder
    class_folder = os.path.join(output_root, class_name)
    os.makedirs(class_folder, exist_ok=True)

    # Read DICOM
    ds = pydicom.dcmread(dicom_path)
    image = ds.pixel_array.astype(np.float32)

    # Normalize
    image = (image - image.min()) / (image.max() - image.min())
    image = (image * 255).astype(np.uint8)

    # Save image
    output_path = os.path.join(class_folder, patient_id + ".png")
    cv2.imwrite(output_path, image)

print("✅ All matching DICOM files processed and saved")

Processing 1/30227: 0004cfab-14fd-4e49-80ba-63a80b6bddd6 -> No Lung Opacity
Processing 2/30227: 00313ee0-9eaa-42f4-b0ab-c148ed3241cd -> No Lung Opacity
Processing 3/30227: 00322d4d-1c29-4943-afc9-b6754be640eb -> No Lung Opacity
Processing 4/30227: 003d8fa0-6bf1-40ed-b54c-ac657f8495c5 -> Normal
Processing 5/30227: 00436515-870c-4b36-a041-de91049b9ab4 -> Lung Opacity
Processing 6/30227: 00436515-870c-4b36-a041-de91049b9ab4 -> Lung Opacity
Processing 7/30227: 00569f44-917d-4c86-a842-81832af98c30 -> No Lung Opacity
Processing 8/30227: 006cec2e-6ce2-4549-bffa-eadfcd1e9970 -> No Lung Opacity
Processing 9/30227: 00704310-78a8-4b38-8475-49f4573b2dbb -> Lung Opacity
Processing 10/30227: 00704310-78a8-4b38-8475-49f4573b2dbb -> Lung Opacity
Processing 11/30227: 008c19e8-a820-403a-930a-bc74a4053664 -> No Lung Opacity
Processing 12/30227: 009482dc-3db5-48d4-8580-5c89c4f01334 -> Normal
Processing 13/30227: 009eb222-eabc-4150-8121-d5a6d06b8ebf -> Normal
Processing 14/30227: 00a85be6-6eb0-421d-8acf-ff2dc0007e8a -> Normal
Processing 15/30227: 00aecb01-a116-45a2-956c-08d2fa55433f -> Lung Opacity
Processing 16/30227: 00aecb01-a116-45a2-956c-08d2fa55433f -> Lung Opacity
Processing 17/30227: 00c0b293-48e7-4e16-ac76-9269ba535a62 -> Lung Opacity
Processing 18/30227: 00c0b293-48e7-4e16-ac76-9269ba535a62 -> Lung Opacity
Processing 19/30227: 00d7c36e-3cdf-4df6-ac03-6c30cdc8e85b -> No Lung Opacity
Processing 20/30227: 00f08de1-517e-4652-a04f-d1dc9ee48593 -> Lung Opacity
Processing 21/30227: 00f08de1-517e-4652-a04f-d1dc9ee48593 -> Lung Opacity
Processing 22/30227: 00f87de5-5fe0-4921-93ea-914d7e683266 -> Normal
Processing 23/30227: 0100515c-5204-4f31-98e0-f35e4b00004a -> Lung Opacity
Processing 24/30227: 01027bc3-dc40-4165-a6c3-d6be2cb7ca34 -> Normal
Processing 25/30227: 010ccb9f-6d46-4380-af11-84f87397a1b8 -> Lung Opacity
Processing 26/30227: 010ccb9f-6d46-4380-af11-84f87397a1b8 -> Lung Opacity
Processing 27/30227: 011d6f51-b732-4d45-a84d-90477325ef2d -> No Lung Opacity
Processing 28/30227: 012a5620-d082-4bb8-9b3b-e72d8938000c -> Lung Opacity
Processing 29/30227: 012a5620-d082-4bb8-9b3b-e72d8938000c -> Lung Opacity
Processing 30/30227: 014b7b58-f641-4477-8bbc-ae6f337745d6 -> No Lung Opacity
Processing 31/30227: 01538c3b-3de9-4fbb-95a8-732235821bbf -> No Lung Opacity
Processing 32/30227: 016b1f90-bb9a-4d3a-9c38-74af5fffd5b5 -> No Lung Opacity
Processing 33/30227: 0174c4bb-28f5-41e3-a13f-a396badc18bd -> Lung Opacity
Processing 34/30227: 0174c4bb-28f5-41e3-a13f-a396badc18bd -> Lung Opacity
Processing 35/30227: 017c7b5b-618e-4bc9-943c-04c6a988d992 -> Normal
Processing 36/30227: 019ca122-9cdf-4704-b7a9-449c8a1c263e -> Normal
Processing 37/30227: 019d950b-dd38-4cf3-a686-527a75728be6 -> Lung Opacity
Processing 38/30227: 019d950b-dd38-4cf3-a686-527a75728be6 -> Lung Opacity
Processing 39/30227: 019e035e-2f82-4c66-a198-57422a27925f -> No Lung Opacity
Processing 40/30227: 01a4059c-22f7-4f51-8a27-50aff0b3aeb3 -> Normal
Processing 41/30227: 01a5594f-e5d4-4f7a-b79d-3f57559fe37b -> No Lung Opacity
Processing 42/30227: 01a6eaa6-222f-4ea8-9874-bbd89dc1a1ce -> Lung Opacity
Processing 43/30227: 01a6eaa6-222f-4ea8-9874-bbd89dc1a1ce -> Lung Opacity
Processing 44/30227: 01a7353d-25bb-4ff8-916b-f50dd541dccf -> Lung Opacity
Processing 45/30227: 01a7353d-25bb-4ff8-916b-f50dd541dccf -> Lung Opacity
Processing 46/30227: 01aad2a6-3b93-45e3-bf37-2d73348cb6fc -> Normal
Processing 47/30227: 01adfd2f-7bc7-4cef-ab68-a0992752b620 -> Lung Opacity
Processing 48/30227: 01b15f07-1149-4ff8-9756-bc821e41b97c -> Normal
Processing 49/30227: 01b56434-4dd9-4994-bcc5-0b70a36e415a -> No Lung Opacity
Processing 50/30227: 01b9e362-4950-40f5-88fa-7557ac2a45bb -> Lung Opacity
Processing 51/30227: 01b9e362-4950-40f5-88fa-7557ac2a45bb -> Lung Opacity
Processing 52/30227: 01be392f-a46d-4aef-a57e-9cd1a80dd47e -> Lung Opacity
Processing 53/30227: 01be392f-a46d-4aef-a57e-9cd1a80dd47e -> Lung Opacity
Processing 54/30227: 01be3fe5-4a91-4c57-9af6-305966a7d0aa -> Normal
Processing 55/30227: 01c09fb1-a917-46ee-8d94-44f844a4eb85 -> No Lung Opacity
Processing 56/30227: 01c0b605-0a82-401b-9649-81252304ac45 -> Normal
Processing 57/30227: 01c7cc7c-7004-441f-9049-77b7b444dd6b -> No Lung Opacity
Processing 58/30227: 01cad8d0-45cd-4603-b099-94055d322310 -> Lung Opacity
Processing 59/30227: 01cad8d0-45cd-4603-b099-94055d322310 -> Lung Opacity
Processing 60/30227: 01cc7c75-4498-43ab-b650-5553d0507f76 -> Normal
Processing 61/30227: 01cd2ba5-2baf-44b2-bf15-ee57e1ea4599 -> Lung Opacity
Processing 62/30227: 01cfa23b-cc98-43af-a61b-56915f90b7ef -> No Lung Opacity
Processing 63/30227: 01d1f0be-5216-4af5-b2dc-a160c1c56122 -> No Lung Opacity
Processing 64/30227: 01d4fa0f-97a0-4522-b0d8-134400db2a3e -> Lung Opacity
Processing 65/30227: 01d4fa0f-97a0-4522-b0d8-134400db2a3e -> Lung Opacity
Processing 66/30227: 01d72346-4459-4eaa-8a19-d3c92121d17f -> No Lung Opacity
Processing 67/30227: 01dc817c-3cfa-49fe-8662-518edc30652a -> Lung Opacity
Processing 68/30227: 01e16ddb-682d-4901-b56d-8686c4f9f976 -> No Lung Opacity
Processing 69/30227: 01e4fd43-4f2c-421f-bd68-c756dceb5742 -> Normal
Processing 70/30227: 01e800d4-4d8d-4ef5-a40a-f37b923bb7ad -> No Lung Opacity
Processing 71/30227: 01ee3bcb-d6a8-4586-b0a5-9647969da07d -> No Lung Opacity
Processing 72/30227: 01ef1712-90a6-4946-ad86-fc76b0cf2d3b -> Normal
Processing 73/30227: 01ef449e-d493-4db2-9162-d83c69f90f40 -> No Lung Opacity
Processing 74/30227: 01f0d9cc-f69e-471a-987a-be73a36e18cc -> Normal
Processing 75/30227: 01f0f4bf-e678-430e-b43d-2968e2c4976c -> Normal
Processing 76/30227: 01f11e57-5c11-4ab0-9312-d88c3826721c -> Normal
Processing 77/30227: 01f3abc2-33c7-4ea2-a599-dc49b76fcfae -> Lung Opacity
Processing 78/30227: 01f3abc2-33c7-4ea2-a599-dc49b76fcfae -> Lung Opacity
Processing 79/30227: 01f4cd36-caa1-480f-9d8c-92e80cf7b197 -> Normal
Processing 80/30227: 01f6bf01-9887-498c-ab11-1d10c6a22221 -> No Lung Opacity
Processing 81/30227: 01fa0f5e-00c3-41cb-b5c7-10600c8633ae -> Lung Opacity
Processing 82/30227: 01fa0f5e-00c3-41cb-b5c7-10600c8633ae -> Lung Opacity
Processing 83/30227: 01fdfd88-7607-48b9-ba05-a36e8b6fd19b -> Lung Opacity
Processing 84/30227: 01fdfd88-7607-48b9-ba05-a36e8b6fd19b -> Lung Opacity
Processing 85/30227: 01fe92f7-ff87-4f9e-9077-e00e670d1b47 -> Normal
Processing 86/30227: 02002619-3dea-4038-8d4d-458db30ed8de -> Lung Opacity
Processing 87/30227: 02002619-3dea-4038-8d4d-458db30ed8de -> Lung Opacity
Processing 88/30227: 020380f8-5c5a-4ded-bdf3-9ce3036945b4 -> Lung Opacity
Processing 89/30227: 020380f8-5c5a-4ded-bdf3-9ce3036945b4 -> Lung Opacity
Processing 90/30227: 02051597-8a40-4586-88e1-8e62e421981f -> No Lung Opacity
Processing 91/30227: 02099738-7465-4786-b71c-de8cdac477c3 -> Lung Opacity
Processing 92/30227: 02099738-7465-4786-b71c-de8cdac477c3 -> Lung Opacity
Processing 93/30227: 020a16e3-baf9-4cf0-859c-c79b5253d717 -> Lung Opacity
Processing 94/30227: 020a16e3-baf9-4cf0-859c-c79b5253d717 -> Lung Opacity
Processing 95/30227: 020fb648-3b1e-404a-a0b4-f25d6b277c1a -> Normal
Processing 96/30227: 021443b8-0e56-4ce2-87e2-53302d8441ca -> No Lung Opacity
Processing 97/30227: 0216bae7-3ab6-4857-8cc1-3afe8dab3964 -> No Lung Opacity
Processing 98/30227: 02285fa4-35b7-4af6-b88f-3cac45a7f5c8 -> Lung Opacity
Processing 99/30227: 022b7bbd-963b-49ea-afd7-b6b7986da555 -> Normal
Processing 100/30227: 024cff3e-86d2-4658-b204-79b94b74b94f -> No Lung Opacity
Processing 101/30227: 0280a39c-4891-4a7b-8073-710c3f5577a3 -> Normal
Processing 102/30227: 029216c8-ea0d-47bb-88fd-bf611cc5d1fc -> Normal
Processing 103/30227: 0294b4aa-5614-4b33-80a4-2c31b639e5b3 -> Lung Opacity
Processing 104/30227: 0294b4aa-5614-4b33-80a4-2c31b639e5b3 -> Lung Opacity
Processing 105/30227: 0295573e-1bbe-4f14-83c2-32449fa79f10 -> Normal
Processing 106/30227: 02b20ea4-9c01-48b2-b3b3-5dae20e80095 -> No Lung Opacity
Processing 107/30227: 02c2331d-b3fa-4d55-bf86-f0efbd589c86 -> No Lung Opacity
Processing 108/30227: 02c34d5b-16e9-412e-a385-ccd8cbceae16 -> Lung Opacity
Processing 109/30227: 02c34d5b-16e9-412e-a385-ccd8cbceae16 -> Lung Opacity
Processing 110/30227: 02de2d68-b7f9-428b-ac12-0cb8f56a0145 -> No Lung Opacity
Processing 111/30227: 02e93c9a-c063-4bf2-9fa1-cb26692d58f8 -> Lung Opacity
Processing 112/30227: 02ea6b76-4189-47c5-a8bf-70590f84ebd8 -> Lung Opacity
Processing 113/30227: 02ea6b76-4189-47c5-a8bf-70590f84ebd8 -> Lung Opacity
Processing 114/30227: 02f6ab3b-7793-4d67-87e3-868911a399b7 -> Normal
Processing 115/30227: 0324368b-3c2f-464a-8b1a-f72113718c38 -> No Lung Opacity
Processing 116/30227: 03249840-0a17-448c-bf41-7e156428ab59 -> Lung Opacity
Processing 117/30227: 03249840-0a17-448c-bf41-7e156428ab59 -> Lung Opacity
Processing 118/30227: 035789b1-3736-405d-9910-f8f23c62ae9f -> Lung Opacity
Processing 119/30227: 035789b1-3736-405d-9910-f8f23c62ae9f -> Lung Opacity
Processing 120/30227: 03682e3c-d601-4e35-9ba5-06e85bba5c7c -> Normal
Processing 121/30227: 037e59c2-5753-4daa-b74f-856694b81729 -> No Lung Opacity
Processing 122/30227: 0385fdea-9b37-4039-b10c-d3094f6afdfa -> No Lung Opacity
Processing 123/30227: 03a9498c-549d-4e7d-800b-e74797f7f625 -> Lung Opacity
Processing 124/30227: 03a9498c-549d-4e7d-800b-e74797f7f625 -> Lung Opacity
Processing 125/30227: 03a9498c-549d-4e7d-800b-e74797f7f625 -> Lung Opacity
Processing 126/30227: 03ab53d0-0a93-43f7-bfb7-4fc5b4db75dc -> No Lung Opacity
Processing 127/30227: 03ae75b6-45a7-4a68-9871-f07b82b17bf6 -> Lung Opacity
Processing 128/30227: 03ae75b6-45a7-4a68-9871-f07b82b17bf6 -> Lung Opacity
Processing 129/30227: 03b10fa5-e7c3-4726-818f-ecbace9da737 -> Normal
Processing 130/30227: 03c149d1-e420-40bf-8d60-f98d0fff1d48 -> No Lung Opacity
Processing 131/30227: 03cd7a5b-d5d7-40a1-81b1-c4264920530a -> Lung Opacity
Processing 132/30227: 03cd7a5b-d5d7-40a1-81b1-c4264920530a -> Lung Opacity
Processing 133/30227: 03d00867-fe6d-47b5-9a14-3f03f736e69a -> No Lung Opacity
Processing 134/30227: 03d92597-3e33-4fdf-8db5-a27cf5b8d3eb -> Lung Opacity
Processing 135/30227: 03da08b4-9f24-4822-8b2b-4abf27e3c9a8 -> Normal
Processing 136/30227: 03e9a70f-3de8-4e13-b3f2-9dd6d75f496d -> Lung Opacity
Processing 137/30227: 03e9a70f-3de8-4e13-b3f2-9dd6d75f496d -> Lung Opacity
Processing 138/30227: 03edb5ed-9e76-4abe-bc35-7bc95fea7e6a -> Lung Opacity
Processing 139/30227: 03edb5ed-9e76-4abe-bc35-7bc95fea7e6a -> Lung Opacity
Processing 140/30227: 03f075e3-c8e8-4401-882e-645ad489926f -> No Lung Opacity
Processing 141/30227: 03f43232-8362-4a4b-8632-aa336ce7ac08 -> Normal
Processing 142/30227: 03f43302-39f0-48a1-ae3d-0c6c611b9302 -> Normal
Processing 143/30227: 0404639a-94b5-40c8-af85-8b0c6a972b01 -> No Lung Opacity
Processing 144/30227: 040784f9-bad4-4c22-98d8-b5244637a2c1 -> No Lung Opacity
Processing 145/30227: 040a0743-f663-4746-8224-f0e3bacc7ba5 -> Lung Opacity
Processing 146/30227: 040a0743-f663-4746-8224-f0e3bacc7ba5 -> Lung Opacity
Processing 147/30227: 040a0743-f663-4746-8224-f0e3bacc7ba5 -> Lung Opacity
Processing 148/30227: 041bf0ac-a841-4c4a-9f91-45f4b3b34671 -> No Lung Opacity
Processing 149/30227: 0425c2d3-5491-42af-8284-a3ee2f3819dc -> No Lung Opacity
Processing 150/30227: 042bde1a-88c1-4ae5-af0c-1a409e1e09ee -> Normal
Processing 151/30227: 043cf55e-48db-407e-b8a3-e4b2d45a3131 -> No Lung Opacity
Processing 152/30227: 04616bb0-77ac-4ba0-816f-7ddd96f60713 -> No Lung Opacity
Processing 153/30227: 04707463-aae0-4989-ae73-f9162275444e -> Normal
Processing 154/30227: 0499513a-5d48-4cf9-aac8-115e2a52fe1a -> Lung Opacity
Processing 155/30227: 0499513a-5d48-4cf9-aac8-115e2a52fe1a -> Lung Opacity
Processing 156/30227: 049d7317-5a8b-4fc4-b81f-159fe6b45a92 -> Lung Opacity
Processing 157/30227: 04a6aa6d-bd6d-48b1-822b-21b81c4bdf3a -> Lung Opacity
Processing 158/30227: 04d59a79-e659-49ca-8790-511f89ac3e1b -> Lung Opacity
Processing 159/30227: 04dd9347-6215-4b34-a98f-a73e577aff9d -> Lung Opacity
Processing 160/30227: 0503aac4-3d6d-416c-94d7-16fc3339ee61 -> No Lung Opacity
Processing 161/30227: 05073cbd-ad54-456d-9de6-b468db719b57 -> Normal
Processing 162/30227: 05083068-f4df-464a-b669-3c084ee05f1f -> Lung Opacity
Processing 163/30227: 0516bfd6-2004-48bb-bbb5-e44ae173bcbd -> No Lung Opacity
Processing 164/30227: 051e6e97-fda7-4b5c-8d5f-084bf3607d22 -> Lung Opacity
Processing 165/30227: 052e09c0-6747-4f72-8e71-96fcc489043a -> No Lung Opacity
Processing 166/30227: 053f237f-c835-4067-8a74-a0b7641bdaca -> Normal
Processing 167/30227: 053f400c-145d-4770-841c-3ea961bb3644 -> Normal
Processing 168/30227: 05576ba5-4a1e-4533-a6e3-9eee9a56368f -> No Lung Opacity
Processing 169/30227: 056c11ef-e99e-444b-824f-734a32ea40d2 -> No Lung Opacity
Processing 170/30227: 056d6cc6-fb4a-48a5-808b-b775d29a438a -> No Lung Opacity
Processing 171/30227: 056f6beb-c3c8-4ee3-8db5-d1b50aabf7c9 -> No Lung Opacity
Processing 172/30227: 056fb495-574d-4b37-9f89-77b9ced2ef43 -> Normal
Processing 173/30227: 0587782c-ac6b-4ae1-8ffb-ce894d09f75e -> Lung Opacity
Processing 174/30227: 0598a87e-6a8a-4439-a6ec-cd3395636b30 -> Normal
Processing 175/30227: 059f1e59-573c-49d1-ac78-3323a2ff047f -> Lung Opacity
Processing 176/30227: 05b5185a-e24a-424e-a62f-4e32c1e5a4b3 -> No Lung Opacity
Processing 177/30227: 05b7f19b-58ba-423a-89a6-5975679b2e15 -> No Lung Opacity
Processing 178/30227: 05b91b32-5635-4071-b45d-6a73f8eea918 -> Lung Opacity
Processing 179/30227: 05b91b32-5635-4071-b45d-6a73f8eea918 -> Lung Opacity
Processing 180/30227: 05b970e1-b223-4c17-a6a8-3f78c43c5308 -> Lung Opacity
Processing 181/30227: 05b970e1-b223-4c17-a6a8-3f78c43c5308 -> Lung Opacity
Processing 182/30227: 05bb6f8d-453b-4e56-ae92-2600e058ba65 -> Lung Opacity
Processing 183/30227: 05bb6f8d-453b-4e56-ae92-2600e058ba65 -> Lung Opacity
Processing 184/30227: 05be93e5-70aa-4879-bf06-6c866bde90d7 -> No Lung Opacity
Processing 185/30227: 05bfde5b-5626-4a1d-84c1-ea6ef456d409 -> No Lung Opacity
Processing 186/30227: 05c4f636-2c27-4b78-b874-878f499813aa -> No Lung Opacity
Processing 187/30227: 05c8ec6f-c41d-4dbe-a6a0-2875334b0b9e -> Normal
Processing 188/30227: 05c9c22a-fe11-4c93-bcb6-67900893db3b -> No Lung Opacity
Processing 189/30227: 05cba281-13bd-4a59-8a93-3278cef10b30 -> No Lung Opacity
Processing 190/30227: 05cd4a95-8187-41ac-929c-226015cceefb -> Normal
Processing 191/30227: 05d16b06-ffb2-40ab-b64a-299448999f72 -> Normal
Processing 192/30227: 05d3817a-5535-4e77-8dda-d4412e496c81 -> Lung Opacity
Processing 193/30227: 05d3817a-5535-4e77-8dda-d4412e496c81 -> Lung Opacity
Processing 194/30227: 05d3b194-78bb-4fe9-aa1c-0f1d76e5641d -> Normal
Processing 195/30227: 05d4d725-02a2-4c90-8ef8-463217889ba8 -> Lung Opacity
Processing 196/30227: 05d4d725-02a2-4c90-8ef8-463217889ba8 -> Lung Opacity
Processing 197/30227: 05dad446-45f7-44df-bd2f-4673d9502348 -> Lung Opacity
Processing 198/30227: 05dc3a75-2069-4f66-b5b0-ce7fd9efe60f -> No Lung Opacity
Processing 199/30227: 05e6c2e5-897d-49d7-a35f-c0fd707a2992 -> No Lung Opacity
Processing 200/30227: 05e79372-5e61-4957-bedf-c2c51a0757ad -> No Lung Opacity
Processing 201/30227: 05ead813-3c04-4e42-a5e1-4ca43294ece9 -> Lung Opacity
Processing 202/30227: 05ee72bf-6d12-4ac5-a47e-f43a7ea52a40 -> Normal
Processing 203/30227: 05eebe4c-bca2-40d4-bb20-54fc60e2bcea -> Lung Opacity
Processing 204/30227: 05eebe4c-bca2-40d4-bb20-54fc60e2bcea -> Lung Opacity
Processing 205/30227: 05f42ea0-fa18-47ba-80a7-e070307300bf -> No Lung Opacity
Processing 206/30227: 05f6eacc-e1a9-4b88-a0ec-f4ab5ba72e93 -> Normal
Processing 207/30227: 05f88159-8c6e-4d9a-92a8-a20c6fb2930d -> Normal
Processing 208/30227: 05f9a259-1b07-4e83-8e30-6b01f3ae1cf1 -> No Lung Opacity
Processing 209/30227: 05fa458a-9e6a-4e02-b85c-c8d67c3161cf -> Normal
Processing 210/30227: 05fb0374-ab2d-4cf4-bb36-ce56fb2c28a5 -> Lung Opacity
Processing 211/30227: 05fdba93-7205-4bff-ab67-649684bff036 -> No Lung Opacity
Processing 212/30227: 05fe70c1-4cc1-42fb-9303-083fd29dac0f -> Lung Opacity
Processing 213/30227: 05fe7d73-5c8c-4349-88c4-2071a00d6d81 -> Lung Opacity
Processing 214/30227: 05fe7d73-5c8c-4349-88c4-2071a00d6d81 -> Lung Opacity
Processing 215/30227: 05ff7ddc-3fb7-4378-ac14-a10a08c64aaf -> No Lung Opacity
Processing 216/30227: 06089341-a69b-4777-817b-041be894b436 -> Lung Opacity
Processing 217/30227: 06089341-a69b-4777-817b-041be894b436 -> Lung Opacity
Processing 218/30227: 0609cacd-b9a6-485f-a6f1-5bb7b88db8dd -> Normal
Processing 219/30227: 0609fbd5-ef5c-4fdc-a51d-9fa0f05ea481 -> No Lung Opacity
Processing 220/30227: 060c4f8a-f04f-4f46-88fc-3d0b90f3608c -> No Lung Opacity
Processing 221/30227: 06155af4-88f1-48b3-8860-27578f1b2e04 -> Lung Opacity
Processing 222/30227: 061628a9-8a6d-4e01-8f26-b7a6cca2b13d -> No Lung Opacity
Processing 223/30227: 061664a4-6a23-4cb2-a0da-0c5712b6e0a6 -> Lung Opacity
Processing 224/30227: 061664a4-6a23-4cb2-a0da-0c5712b6e0a6 -> Lung Opacity
Processing 225/30227: 0618a5bc-196d-4afc-9ac4-d0aa940c6e03 -> Lung Opacity
Processing 226/30227: 0618f099-05dd-41d8-bf4d-b5ef8400c2e0 -> No Lung Opacity
Processing 227/30227: 06199c4d-5f6f-4736-81b1-07bf5b76bd78 -> Normal
Processing 228/30227: 061b44ff-fd22-473d-853f-81da70e14a63 -> Lung Opacity
Processing 229/30227: 061bb9bf-13c6-4ea0-bd82-5768fb83dff8 -> Lung Opacity
Processing 230/30227: 061bb9bf-13c6-4ea0-bd82-5768fb83dff8 -> Lung Opacity
Processing 231/30227: 061ccabd-b0cf-4238-a053-28a1960c1923 -> Normal
Processing 232/30227: 061d0ff4-a611-42ce-b780-1d1eb55e50ab -> Lung Opacity
Processing 233/30227: 061d0ff4-a611-42ce-b780-1d1eb55e50ab -> Lung Opacity
Processing 234/30227: 0620afa3-b2ea-442e-9e4f-c854086ca763 -> Lung Opacity
Processing 235/30227: 06216b5c-c03f-4562-bfec-bec5235943d2 -> No Lung Opacity
Processing 236/30227: 062374a3-6ca1-48d2-aa3c-820053773b54 -> No Lung Opacity
Processing 237/30227: 0623ea89-c89c-4743-b492-55e398de4c9b -> Normal
Processing 238/30227: 06250f9d-5ad9-44ca-9283-dbf787e2ad22 -> Lung Opacity
Processing 239/30227: 06250f9d-5ad9-44ca-9283-dbf787e2ad22 -> Lung Opacity
Processing 240/30227: 06327569-4e4f-4fdc-a116-db367c079669 -> Lung Opacity
Processing 241/30227: 0634d937-1be6-475e-a5fd-dc9a2b6a8da6 -> No Lung Opacity
Processing 242/30227: 0637b804-e693-48d1-8716-f7c63ce6162a -> Lung Opacity
Processing 243/30227: 0638126f-126f-4f53-befe-538ff87597c6 -> No Lung Opacity
Processing 244/30227: 0638709c-d31d-4a59-a9e4-fc408ae36145 -> Lung Opacity
Processing 245/30227: 0638709c-d31d-4a59-a9e4-fc408ae36145 -> Lung Opacity
Processing 246/30227: 063a4fc6-ef5d-4370-8b0b-c2752a4c905c -> No Lung Opacity
Processing 247/30227: 063f63c9-7e5b-4360-8d19-0060d849fdbc -> Normal
Processing 248/30227: 063fed6c-4ecd-4a74-8f0d-c7a906a3afa4 -> Lung Opacity
Processing 249/30227: 063fed6c-4ecd-4a74-8f0d-c7a906a3afa4 -> Lung Opacity
Processing 250/30227: 06415658-2590-4c38-a682-81acf9ef9a14 -> No Lung Opacity
Processing 251/30227: 06420c87-02ee-4315-aa3a-63e911174435 -> Lung Opacity
Processing 252/30227: 06420c87-02ee-4315-aa3a-63e911174435 -> Lung Opacity
Processing 253/30227: 06463240-3dd5-4d64-ad20-0956af60d1a2 -> No Lung Opacity
Processing 254/30227: 064bd2d6-5cc4-4933-957f-c880f44e2de2 -> No Lung Opacity
Processing 255/30227: 064c4273-4f62-417e-be2b-c30cd480fa82 -> No Lung Opacity
Processing 256/30227: 065158ed-021d-4d2d-a2e2-79b69a03853d -> Normal
Processing 257/30227: 06550cfd-e9d5-415e-bae9-3146329ed9e6 -> Lung Opacity
Processing 258/30227: 06550cfd-e9d5-415e-bae9-3146329ed9e6 -> Lung Opacity
Processing 259/30227: 065b3a2f-1af3-4ebd-a740-9e49f9c685db -> No Lung Opacity
Processing 260/30227: 065b79b6-9a76-4b92-9417-de09b3d97cd5 -> No Lung Opacity
Processing 261/30227: 06605bfa-0370-4979-a2bd-11173002abd1 -> Normal
Processing 262/30227: 06634f15-9c78-47a1-97eb-f10f4c210765 -> Lung Opacity
Processing 263/30227: 06634f15-9c78-47a1-97eb-f10f4c210765 -> Lung Opacity
Processing 264/30227: 0666201a-fab4-4828-81dd-73292312c766 -> Normal
Processing 265/30227: 06697be9-b1ab-444c-af0d-fd11a053f2b3 -> Lung Opacity
Processing 266/30227: 06697be9-b1ab-444c-af0d-fd11a053f2b3 -> Lung Opacity
Processing 267/30227: 066d9e27-e48f-4453-b1e1-d73c34910722 -> Lung Opacity
Processing 268/30227: 066e0d5c-0f47-425c-aa7f-9003c355086b -> No Lung Opacity
Processing 269/30227: 06737bed-8dc1-47d9-8c30-324282dcc84d -> Lung Opacity

KeyboardInterrupt:

In [29]:
import os
import pandas as pd
import pydicom
import numpy as np
import cupy as cp
import cv2

# 🔥 Force GPU usage (will crash if GPU not detected)
assert cp.cuda.runtime.getDeviceCount() > 0, "❌ GPU NOT DETECTED"

dicom_dir = r"D:\Project\AI That Explains Medical Images Like a Doctor\Another way\Dataset\stage_2_train_images"
output_root = r"D:\Project\AI That Explains Medical Images Like a Doctor\Another way\Dataset\images"

os.makedirs(output_root, exist_ok=True)

i = 0
for idx in range(len(df)):
    patient_id = str(df.loc[idx, 'patientId'])
    class_name = str(df2.loc[idx, 'class'])

    print(f"Processing {i+1}/{len(df)}: {patient_id} -> {class_name}")
    i += 1

    dicom_path = os.path.join(dicom_dir, patient_id + ".dcm")

    if not os.path.exists(dicom_path):
        print(f"❌ Missing: {patient_id}.dcm")
        continue

    class_folder = os.path.join(output_root, class_name)
    os.makedirs(class_folder, exist_ok=True)

    # ❌ CPU (cannot be changed)
    ds = pydicom.dcmread(dicom_path)
    image = ds.pixel_array.astype(np.float32)

    # ✅ CPU → GPU
    gpu_img = cp.asarray(image)

    # 🚀 GPU NORMALIZATION
    gpu_img = (gpu_img - cp.min(gpu_img)) / (cp.max(gpu_img) - cp.min(gpu_img))
    gpu_img = (gpu_img * 255).astype(cp.uint8)

    # ✅ GPU → CPU (only for saving)
    final_img = cp.asnumpy(gpu_img)

    output_path = os.path.join(class_folder, patient_id + ".png")
    cv2.imwrite(output_path, final_img)

print("🔥 All matching DICOM files processed using GPU")

Processing 1/30227: 0004cfab-14fd-4e49-80ba-63a80b6bddd6 -> No Lung Opacity
Processing 2/30227: 00313ee0-9eaa-42f4-b0ab-c148ed3241cd -> No Lung Opacity
Processing 3/30227: 00322d4d-1c29-4943-afc9-b6754be640eb -> No Lung Opacity
Processing 4/30227: 003d8fa0-6bf1-40ed-b54c-ac657f8495c5 -> Normal
Processing 5/30227: 00436515-870c-4b36-a041-de91049b9ab4 -> Lung Opacity
Processing 6/30227: 00436515-870c-4b36-a041-de91049b9ab4 -> Lung Opacity
Processing 7/30227: 00569f44-917d-4c86-a842-81832af98c30 -> No Lung Opacity
Processing 8/30227: 006cec2e-6ce2-4549-bffa-eadfcd1e9970 -> No Lung Opacity
Processing 9/30227: 00704310-78a8-4b38-8475-49f4573b2dbb -> Lung Opacity
Processing 10/30227: 00704310-78a8-4b38-8475-49f4573b2dbb -> Lung Opacity
Processing 11/30227: 008c19e8-a820-403a-930a-bc74a4053664 -> No Lung Opacity
Processing 12/30227: 009482dc-3db5-48d4-8580-5c89c4f01334 -> Normal
Processing 13/30227: 009eb222-eabc-4150-8121-d5a6d06b8ebf -> Normal
Processing 14/30227: 00a85be6-6eb0-421d-8acf-ff2dc0007e8a -> Normal
Processing 15/30227: 00aecb01-a116-45a2-956c-08d2fa55433f -> Lung Opacity
Processing 16/30227: 00aecb01-a116-45a2-956c-08d2fa55433f -> Lung Opacity
Processing 17/30227: 00c0b293-48e7-4e16-ac76-9269ba535a62 -> Lung Opacity
Processing 18/30227: 00c0b293-48e7-4e16-ac76-9269ba535a62 -> Lung Opacity
Processing 19/30227: 00d7c36e-3cdf-4df6-ac03-6c30cdc8e85b -> No Lung Opacity
Processing 20/30227: 00f08de1-517e-4652-a04f-d1dc9ee48593 -> Lung Opacity
Processing 21/30227: 00f08de1-517e-4652-a04f-d1dc9ee48593 -> Lung Opacity
Processing 22/30227: 00f87de5-5fe0-4921-93ea-914d7e683266 -> Normal
Processing 23/30227: 0100515c-5204-4f31-98e0-f35e4b00004a -> Lung Opacity
Processing 24/30227: 01027bc3-dc40-4165-a6c3-d6be2cb7ca34 -> Normal
Processing 25/30227: 010ccb9f-6d46-4380-af11-84f87397a1b8 -> Lung Opacity
Processing 26/30227: 010ccb9f-6d46-4380-af11-84f87397a1b8 -> Lung Opacity
Processing 27/30227: 011d6f51-b732-4d45-a84d-90477325ef2d -> No Lung Opacity
Processing 28/30227: 012a5620-d082-4bb8-9b3b-e72d8938000c -> Lung Opacity
Processing 29/30227: 012a5620-d082-4bb8-9b3b-e72d8938000c -> Lung Opacity
Processing 30/30227: 014b7b58-f641-4477-8bbc-ae6f337745d6 -> No Lung Opacity
Processing 31/30227: 01538c3b-3de9-4fbb-95a8-732235821bbf -> No Lung Opacity
Processing 32/30227: 016b1f90-bb9a-4d3a-9c38-74af5fffd5b5 -> No Lung Opacity
Processing 33/30227: 0174c4bb-28f5-41e3-a13f-a396badc18bd -> Lung Opacity
Processing 34/30227: 0174c4bb-28f5-41e3-a13f-a396badc18bd -> Lung Opacity
Processing 35/30227: 017c7b5b-618e-4bc9-943c-04c6a988d992 -> Normal
Processing 36/30227: 019ca122-9cdf-4704-b7a9-449c8a1c263e -> Normal
Processing 37/30227: 019d950b-dd38-4cf3-a686-527a75728be6 -> Lung Opacity
Processing 38/30227: 019d950b-dd38-4cf3-a686-527a75728be6 -> Lung Opacity
Processing 39/30227: 019e035e-2f82-4c66-a198-57422a27925f -> No Lung Opacity
Processing 40/30227: 01a4059c-22f7-4f51-8a27-50aff0b3aeb3 -> Normal
Processing 41/30227: 01a5594f-e5d4-4f7a-b79d-3f57559fe37b -> No Lung Opacity
Processing 42/30227: 01a6eaa6-222f-4ea8-9874-bbd89dc1a1ce -> Lung Opacity
Processing 43/30227: 01a6eaa6-222f-4ea8-9874-bbd89dc1a1ce -> Lung Opacity
Processing 44/30227: 01a7353d-25bb-4ff8-916b-f50dd541dccf -> Lung Opacity
Processing 45/30227: 01a7353d-25bb-4ff8-916b-f50dd541dccf -> Lung Opacity
Processing 46/30227: 01aad2a6-3b93-45e3-bf37-2d73348cb6fc -> Normal
Processing 47/30227: 01adfd2f-7bc7-4cef-ab68-a0992752b620 -> Lung Opacity
Processing 48/30227: 01b15f07-1149-4ff8-9756-bc821e41b97c -> Normal
Processing 49/30227: 01b56434-4dd9-4994-bcc5-0b70a36e415a -> No Lung Opacity
Processing 50/30227: 01b9e362-4950-40f5-88fa-7557ac2a45bb -> Lung Opacity
Processing 51/30227: 01b9e362-4950-40f5-88fa-7557ac2a45bb -> Lung Opacity
Processing 52/30227: 01be392f-a46d-4aef-a57e-9cd1a80dd47e -> Lung Opacity
Processing 53/30227: 01be392f-a46d-4aef-a57e-9cd1a80dd47e -> Lung Opacity
Processing 54/30227: 01be3fe5-4a91-4c57-9af6-305966a7d0aa -> Normal
Processing 55/30227: 01c09fb1-a917-46ee-8d94-44f844a4eb85 -> No Lung Opacity
Processing 56/30227: 01c0b605-0a82-401b-9649-81252304ac45 -> Normal
Processing 57/30227: 01c7cc7c-7004-441f-9049-77b7b444dd6b -> No Lung Opacity
Processing 58/30227: 01cad8d0-45cd-4603-b099-94055d322310 -> Lung Opacity
Processing 59/30227: 01cad8d0-45cd-4603-b099-94055d322310 -> Lung Opacity
Processing 60/30227: 01cc7c75-4498-43ab-b650-5553d0507f76 -> Normal
Processing 61/30227: 01cd2ba5-2baf-44b2-bf15-ee57e1ea4599 -> Lung Opacity
Processing 62/30227: 01cfa23b-cc98-43af-a61b-56915f90b7ef -> No Lung Opacity
Processing 63/30227: 01d1f0be-5216-4af5-b2dc-a160c1c56122 -> No Lung Opacity
Processing 64/30227: 01d4fa0f-97a0-4522-b0d8-134400db2a3e -> Lung Opacity
Processing 65/30227: 01d4fa0f-97a0-4522-b0d8-134400db2a3e -> Lung Opacity
Processing 66/30227: 01d72346-4459-4eaa-8a19-d3c92121d17f -> No Lung Opacity
Processing 67/30227: 01dc817c-3cfa-49fe-8662-518edc30652a -> Lung Opacity
Processing 68/30227: 01e16ddb-682d-4901-b56d-8686c4f9f976 -> No Lung Opacity
Processing 69/30227: 01e4fd43-4f2c-421f-bd68-c756dceb5742 -> Normal
Processing 70/30227: 01e800d4-4d8d-4ef5-a40a-f37b923bb7ad -> No Lung Opacity
Processing 71/30227: 01ee3bcb-d6a8-4586-b0a5-9647969da07d -> No Lung Opacity
Processing 72/30227: 01ef1712-90a6-4946-ad86-fc76b0cf2d3b -> Normal
Processing 73/30227: 01ef449e-d493-4db2-9162-d83c69f90f40 -> No Lung Opacity
Processing 74/30227: 01f0d9cc-f69e-471a-987a-be73a36e18cc -> Normal
Processing 75/30227: 01f0f4bf-e678-430e-b43d-2968e2c4976c -> Normal
Processing 76/30227: 01f11e57-5c11-4ab0-9312-d88c3826721c -> Normal
Processing 77/30227: 01f3abc2-33c7-4ea2-a599-dc49b76fcfae -> Lung Opacity
Processing 78/30227: 01f3abc2-33c7-4ea2-a599-dc49b76fcfae -> Lung Opacity
Processing 79/30227: 01f4cd36-caa1-480f-9d8c-92e80cf7b197 -> Normal
Processing 80/30227: 01f6bf01-9887-498c-ab11-1d10c6a22221 -> No Lung Opacity
Processing 81/30227: 01fa0f5e-00c3-41cb-b5c7-10600c8633ae -> Lung Opacity
Processing 82/30227: 01fa0f5e-00c3-41cb-b5c7-10600c8633ae -> Lung Opacity
Processing 83/30227: 01fdfd88-7607-48b9-ba05-a36e8b6fd19b -> Lung Opacity
Processing 84/30227: 01fdfd88-7607-48b9-ba05-a36e8b6fd19b -> Lung Opacity
Processing 85/30227: 01fe92f7-ff87-4f9e-9077-e00e670d1b47 -> Normal
Processing 86/30227: 02002619-3dea-4038-8d4d-458db30ed8de -> Lung Opacity
Processing 87/30227: 02002619-3dea-4038-8d4d-458db30ed8de -> Lung Opacity
Processing 88/30227: 020380f8-5c5a-4ded-bdf3-9ce3036945b4 -> Lung Opacity
Processing 89/30227: 020380f8-5c5a-4ded-bdf3-9ce3036945b4 -> Lung Opacity
Processing 90/30227: 02051597-8a40-4586-88e1-8e62e421981f -> No Lung Opacity
Processing 91/30227: 02099738-7465-4786-b71c-de8cdac477c3 -> Lung Opacity
Processing 92/30227: 02099738-7465-4786-b71c-de8cdac477c3 -> Lung Opacity
Processing 93/30227: 020a16e3-baf9-4cf0-859c-c79b5253d717 -> Lung Opacity
Processing 94/30227: 020a16e3-baf9-4cf0-859c-c79b5253d717 -> Lung Opacity
Processing 95/30227: 020fb648-3b1e-404a-a0b4-f25d6b277c1a -> Normal
Processing 96/30227: 021443b8-0e56-4ce2-87e2-53302d8441ca -> No Lung Opacity
Processing 97/30227: 0216bae7-3ab6-4857-8cc1-3afe8dab3964 -> No Lung Opacity
Processing 98/30227: 02285fa4-35b7-4af6-b88f-3cac45a7f5c8 -> Lung Opacity
Processing 99/30227: 022b7bbd-963b-49ea-afd7-b6b7986da555 -> Normal
Processing 100/30227: 024cff3e-86d2-4658-b204-79b94b74b94f -> No Lung Opacity
Processing 101/30227: 0280a39c-4891-4a7b-8073-710c3f5577a3 -> Normal
Processing 102/30227: 029216c8-ea0d-47bb-88fd-bf611cc5d1fc -> Normal
Processing 103/30227: 0294b4aa-5614-4b33-80a4-2c31b639e5b3 -> Lung Opacity
Processing 104/30227: 0294b4aa-5614-4b33-80a4-2c31b639e5b3 -> Lung Opacity
Processing 105/30227: 0295573e-1bbe-4f14-83c2-32449fa79f10 -> Normal
Processing 106/30227: 02b20ea4-9c01-48b2-b3b3-5dae20e80095 -> No Lung Opacity
Processing 107/30227: 02c2331d-b3fa-4d55-bf86-f0efbd589c86 -> No Lung Opacity
Processing 108/30227: 02c34d5b-16e9-412e-a385-ccd8cbceae16 -> Lung Opacity
Processing 109/30227: 02c34d5b-16e9-412e-a385-ccd8cbceae16 -> Lung Opacity
Processing 110/30227: 02de2d68-b7f9-428b-ac12-0cb8f56a0145 -> No Lung Opacity
Processing 111/30227: 02e93c9a-c063-4bf2-9fa1-cb26692d58f8 -> Lung Opacity
Processing 112/30227: 02ea6b76-4189-47c5-a8bf-70590f84ebd8 -> Lung Opacity
Processing 113/30227: 02ea6b76-4189-47c5-a8bf-70590f84ebd8 -> Lung Opacity
Processing 114/30227: 02f6ab3b-7793-4d67-87e3-868911a399b7 -> Normal
Processing 115/30227: 0324368b-3c2f-464a-8b1a-f72113718c38 -> No Lung Opacity
Processing 116/30227: 03249840-0a17-448c-bf41-7e156428ab59 -> Lung Opacity
Processing 117/30227: 03249840-0a17-448c-bf41-7e156428ab59 -> Lung Opacity
Processing 118/30227: 035789b1-3736-405d-9910-f8f23c62ae9f -> Lung Opacity
Processing 119/30227: 035789b1-3736-405d-9910-f8f23c62ae9f -> Lung Opacity
Processing 120/30227: 03682e3c-d601-4e35-9ba5-06e85bba5c7c -> Normal
Processing 121/30227: 037e59c2-5753-4daa-b74f-856694b81729 -> No Lung Opacity
Processing 122/30227: 0385fdea-9b37-4039-b10c-d3094f6afdfa -> No Lung Opacity
Processing 123/30227: 03a9498c-549d-4e7d-800b-e74797f7f625 -> Lung Opacity
Processing 124/30227: 03a9498c-549d-4e7d-800b-e74797f7f625 -> Lung Opacity
Processing 125/30227: 03a9498c-549d-4e7d-800b-e74797f7f625 -> Lung Opacity
Processing 126/30227: 03ab53d0-0a93-43f7-bfb7-4fc5b4db75dc -> No Lung Opacity
Processing 127/30227: 03ae75b6-45a7-4a68-9871-f07b82b17bf6 -> Lung Opacity
Processing 128/30227: 03ae75b6-45a7-4a68-9871-f07b82b17bf6 -> Lung Opacity
Processing 129/30227: 03b10fa5-e7c3-4726-818f-ecbace9da737 -> Normal
Processing 130/30227: 03c149d1-e420-40bf-8d60-f98d0fff1d48 -> No Lung Opacity
Processing 131/30227: 03cd7a5b-d5d7-40a1-81b1-c4264920530a -> Lung Opacity
Processing 132/30227: 03cd7a5b-d5d7-40a1-81b1-c4264920530a -> Lung Opacity
Processing 133/30227: 03d00867-fe6d-47b5-9a14-3f03f736e69a -> No Lung Opacity
Processing 134/30227: 03d92597-3e33-4fdf-8db5-a27cf5b8d3eb -> Lung Opacity
Processing 135/30227: 03da08b4-9f24-4822-8b2b-4abf27e3c9a8 -> Normal
Processing 136/30227: 03e9a70f-3de8-4e13-b3f2-9dd6d75f496d -> Lung Opacity
Processing 137/30227: 03e9a70f-3de8-4e13-b3f2-9dd6d75f496d -> Lung Opacity
Processing 138/30227: 03edb5ed-9e76-4abe-bc35-7bc95fea7e6a -> Lung Opacity
Processing 139/30227: 03edb5ed-9e76-4abe-bc35-7bc95fea7e6a -> Lung Opacity
Processing 140/30227: 03f075e3-c8e8-4401-882e-645ad489926f -> No Lung Opacity
Processing 141/30227: 03f43232-8362-4a4b-8632-aa336ce7ac08 -> Normal
Processing 142/30227: 03f43302-39f0-48a1-ae3d-0c6c611b9302 -> Normal
Processing 143/30227: 0404639a-94b5-40c8-af85-8b0c6a972b01 -> No Lung Opacity
Processing 144/30227: 040784f9-bad4-4c22-98d8-b5244637a2c1 -> No Lung Opacity
Processing 145/30227: 040a0743-f663-4746-8224-f0e3bacc7ba5 -> Lung Opacity
Processing 146/30227: 040a0743-f663-4746-8224-f0e3bacc7ba5 -> Lung Opacity
Processing 147/30227: 040a0743-f663-4746-8224-f0e3bacc7ba5 -> Lung Opacity
Processing 148/30227: 041bf0ac-a841-4c4a-9f91-45f4b3b34671 -> No Lung Opacity
Processing 149/30227: 0425c2d3-5491-42af-8284-a3ee2f3819dc -> No Lung Opacity
Processing 150/30227: 042bde1a-88c1-4ae5-af0c-1a409e1e09ee -> Normal
Processing 151/30227: 043cf55e-48db-407e-b8a3-e4b2d45a3131 -> No Lung Opacity
Processing 152/30227: 04616bb0-77ac-4ba0-816f-7ddd96f60713 -> No Lung Opacity
Processing 153/30227: 04707463-aae0-4989-ae73-f9162275444e -> Normal
Processing 154/30227: 0499513a-5d48-4cf9-aac8-115e2a52fe1a -> Lung Opacity
Processing 155/30227: 0499513a-5d48-4cf9-aac8-115e2a52fe1a -> Lung Opacity
Processing 156/30227: 049d7317-5a8b-4fc4-b81f-159fe6b45a92 -> Lung Opacity
Processing 157/30227: 04a6aa6d-bd6d-48b1-822b-21b81c4bdf3a -> Lung Opacity
Processing 158/30227: 04d59a79-e659-49ca-8790-511f89ac3e1b -> Lung Opacity
Processing 159/30227: 04dd9347-6215-4b34-a98f-a73e577aff9d -> Lung Opacity
Processing 160/30227: 0503aac4-3d6d-416c-94d7-16fc3339ee61 -> No Lung Opacity
Processing 161/30227: 05073cbd-ad54-456d-9de6-b468db719b57 -> Normal
Processing 162/30227: 05083068-f4df-464a-b669-3c084ee05f1f -> Lung Opacity
Processing 163/30227: 0516bfd6-2004-48bb-bbb5-e44ae173bcbd -> No Lung Opacity
Processing 164/30227: 051e6e97-fda7-4b5c-8d5f-084bf3607d22 -> Lung Opacity
Processing 165/30227: 052e09c0-6747-4f72-8e71-96fcc489043a -> No Lung Opacity
Processing 166/30227: 053f237f-c835-4067-8a74-a0b7641bdaca -> Normal
Processing 167/30227: 053f400c-145d-4770-841c-3ea961bb3644 -> Normal
Processing 168/30227: 05576ba5-4a1e-4533-a6e3-9eee9a56368f -> No Lung Opacity
Processing 169/30227: 056c11ef-e99e-444b-824f-734a32ea40d2 -> No Lung Opacity
Processing 170/30227: 056d6cc6-fb4a-48a5-808b-b775d29a438a -> No Lung Opacity
Processing 171/30227: 056f6beb-c3c8-4ee3-8db5-d1b50aabf7c9 -> No Lung Opacity
Processing 172/30227: 056fb495-574d-4b37-9f89-77b9ced2ef43 -> Normal
Processing 173/30227: 0587782c-ac6b-4ae1-8ffb-ce894d09f75e -> Lung Opacity
Processing 174/30227: 0598a87e-6a8a-4439-a6ec-cd3395636b30 -> Normal
Processing 175/30227: 059f1e59-573c-49d1-ac78-3323a2ff047f -> Lung Opacity
Processing 176/30227: 05b5185a-e24a-424e-a62f-4e32c1e5a4b3 -> No Lung Opacity
Processing 177/30227: 05b7f19b-58ba-423a-89a6-5975679b2e15 -> No Lung Opacity
Processing 178/30227: 05b91b32-5635-4071-b45d-6a73f8eea918 -> Lung Opacity
Processing 179/30227: 05b91b32-5635-4071-b45d-6a73f8eea918 -> Lung Opacity
Processing 180/30227: 05b970e1-b223-4c17-a6a8-3f78c43c5308 -> Lung Opacity
Processing 181/30227: 05b970e1-b223-4c17-a6a8-3f78c43c5308 -> Lung Opacity
Processing 182/30227: 05bb6f8d-453b-4e56-ae92-2600e058ba65 -> Lung Opacity
Processing 183/30227: 05bb6f8d-453b-4e56-ae92-2600e058ba65 -> Lung Opacity
Processing 184/30227: 05be93e5-70aa-4879-bf06-6c866bde90d7 -> No Lung Opacity
Processing 185/30227: 05bfde5b-5626-4a1d-84c1-ea6ef456d409 -> No Lung Opacity
Processing 186/30227: 05c4f636-2c27-4b78-b874-878f499813aa -> No Lung Opacity
Processing 187/30227: 05c8ec6f-c41d-4dbe-a6a0-2875334b0b9e -> Normal
Processing 188/30227: 05c9c22a-fe11-4c93-bcb6-67900893db3b -> No Lung Opacity
Processing 189/30227: 05cba281-13bd-4a59-8a93-3278cef10b30 -> No Lung Opacity
Processing 190/30227: 05cd4a95-8187-41ac-929c-226015cceefb -> Normal
Processing 191/30227: 05d16b06-ffb2-40ab-b64a-299448999f72 -> Normal
Processing 192/30227: 05d3817a-5535-4e77-8dda-d4412e496c81 -> Lung Opacity
Processing 193/30227: 05d3817a-5535-4e77-8dda-d4412e496c81 -> Lung Opacity
Processing 194/30227: 05d3b194-78bb-4fe9-aa1c-0f1d76e5641d -> Normal
Processing 195/30227: 05d4d725-02a2-4c90-8ef8-463217889ba8 -> Lung Opacity
Processing 196/30227: 05d4d725-02a2-4c90-8ef8-463217889ba8 -> Lung Opacity
Processing 197/30227: 05dad446-45f7-44df-bd2f-4673d9502348 -> Lung Opacity
Processing 198/30227: 05dc3a75-2069-4f66-b5b0-ce7fd9efe60f -> No Lung Opacity
Processing 199/30227: 05e6c2e5-897d-49d7-a35f-c0fd707a2992 -> No Lung Opacity
Processing 200/30227: 05e79372-5e61-4957-bedf-c2c51a0757ad -> No Lung Opacity
Processing 201/30227: 05ead813-3c04-4e42-a5e1-4ca43294ece9 -> Lung Opacity
Processing 202/30227: 05ee72bf-6d12-4ac5-a47e-f43a7ea52a40 -> Normal
Processing 203/30227: 05eebe4c-bca2-40d4-bb20-54fc60e2bcea -> Lung Opacity
Processing 204/30227: 05eebe4c-bca2-40d4-bb20-54fc60e2bcea -> Lung Opacity
Processing 205/30227: 05f42ea0-fa18-47ba-80a7-e070307300bf -> No Lung Opacity
Processing 206/30227: 05f6eacc-e1a9-4b88-a0ec-f4ab5ba72e93 -> Normal
Processing 207/30227: 05f88159-8c6e-4d9a-92a8-a20c6fb2930d -> Normal
Processing 208/30227: 05f9a259-1b07-4e83-8e30-6b01f3ae1cf1 -> No Lung Opacity
Processing 209/30227: 05fa458a-9e6a-4e02-b85c-c8d67c3161cf -> Normal
Processing 210/30227: 05fb0374-ab2d-4cf4-bb36-ce56fb2c28a5 -> Lung Opacity
Processing 211/30227: 05fdba93-7205-4bff-ab67-649684bff036 -> No Lung Opacity
Processing 212/30227: 05fe70c1-4cc1-42fb-9303-083fd29dac0f -> Lung Opacity
Processing 213/30227: 05fe7d73-5c8c-4349-88c4-2071a00d6d81 -> Lung Opacity
Processing 214/30227: 05fe7d73-5c8c-4349-88c4-2071a00d6d81 -> Lung Opacity
Processing 215/30227: 05ff7ddc-3fb7-4378-ac14-a10a08c64aaf -> No Lung Opacity
Processing 216/30227: 06089341-a69b-4777-817b-041be894b436 -> Lung Opacity
Processing 217/30227: 06089341-a69b-4777-817b-041be894b436 -> Lung Opacity
Processing 218/30227: 0609cacd-b9a6-485f-a6f1-5bb7b88db8dd -> Normal
Processing 219/30227: 0609fbd5-ef5c-4fdc-a51d-9fa0f05ea481 -> No Lung Opacity
Processing 220/30227: 060c4f8a-f04f-4f46-88fc-3d0b90f3608c -> No Lung Opacity
Processing 221/30227: 06155af4-88f1-48b3-8860-27578f1b2e04 -> Lung Opacity
Processing 222/30227: 061628a9-8a6d-4e01-8f26-b7a6cca2b13d -> No Lung Opacity
Processing 223/30227: 061664a4-6a23-4cb2-a0da-0c5712b6e0a6 -> Lung Opacity
Processing 224/30227: 061664a4-6a23-4cb2-a0da-0c5712b6e0a6 -> Lung Opacity
Processing 225/30227: 0618a5bc-196d-4afc-9ac4-d0aa940c6e03 -> Lung Opacity
Processing 226/30227: 0618f099-05dd-41d8-bf4d-b5ef8400c2e0 -> No Lung Opacity
Processing 227/30227: 06199c4d-5f6f-4736-81b1-07bf5b76bd78 -> Normal
Processing 228/30227: 061b44ff-fd22-473d-853f-81da70e14a63 -> Lung Opacity
Processing 229/30227: 061bb9bf-13c6-4ea0-bd82-5768fb83dff8 -> Lung Opacity
Processing 230/30227: 061bb9bf-13c6-4ea0-bd82-5768fb83dff8 -> Lung Opacity
Processing 231/30227: 061ccabd-b0cf-4238-a053-28a1960c1923 -> Normal
Processing 232/30227: 061d0ff4-a611-42ce-b780-1d1eb55e50ab -> Lung Opacity
Processing 233/30227: 061d0ff4-a611-42ce-b780-1d1eb55e50ab -> Lung Opacity
Processing 234/30227: 0620afa3-b2ea-442e-9e4f-c854086ca763 -> Lung Opacity
Processing 235/30227: 06216b5c-c03f-4562-bfec-bec5235943d2 -> No Lung Opacity
Processing 236/30227: 062374a3-6ca1-48d2-aa3c-820053773b54 -> No Lung Opacity
Processing 237/30227: 0623ea89-c89c-4743-b492-55e398de4c9b -> Normal
Processing 238/30227: 06250f9d-5ad9-44ca-9283-dbf787e2ad22 -> Lung Opacity
Processing 239/30227: 06250f9d-5ad9-44ca-9283-dbf787e2ad22 -> Lung Opacity
Processing 240/30227: 06327569-4e4f-4fdc-a116-db367c079669 -> Lung Opacity
Processing 241/30227: 0634d937-1be6-475e-a5fd-dc9a2b6a8da6 -> No Lung Opacity
Processing 242/30227: 0637b804-e693-48d1-8716-f7c63ce6162a -> Lung Opacity
Processing 243/30227: 0638126f-126f-4f53-befe-538ff87597c6 -> No Lung Opacity
Processing 244/30227: 0638709c-d31d-4a59-a9e4-fc408ae36145 -> Lung Opacity
Processing 245/30227: 0638709c-d31d-4a59-a9e4-fc408ae36145 -> Lung Opacity
Processing 246/30227: 063a4fc6-ef5d-4370-8b0b-c2752a4c905c -> No Lung Opacity
Processing 247/30227: 063f63c9-7e5b-4360-8d19-0060d849fdbc -> Normal
Processing 248/30227: 063fed6c-4ecd-4a74-8f0d-c7a906a3afa4 -> Lung Opacity
Processing 249/30227: 063fed6c-4ecd-4a74-8f0d-c7a906a3afa4 -> Lung Opacity
Processing 250/30227: 06415658-2590-4c38-a682-81acf9ef9a14 -> No Lung Opacity
Processing 251/30227: 06420c87-02ee-4315-aa3a-63e911174435 -> Lung Opacity
Processing 252/30227: 06420c87-02ee-4315-aa3a-63e911174435 -> Lung Opacity
Processing 253/30227: 06463240-3dd5-4d64-ad20-0956af60d1a2 -> No Lung Opacity
Processing 254/30227: 064bd2d6-5cc4-4933-957f-c880f44e2de2 -> No Lung Opacity
Processing 255/30227: 064c4273-4f62-417e-be2b-c30cd480fa82 -> No Lung Opacity
Processing 256/30227: 065158ed-021d-4d2d-a2e2-79b69a03853d -> Normal
Processing 257/30227: 06550cfd-e9d5-415e-bae9-3146329ed9e6 -> Lung Opacity
Processing 258/30227: 06550cfd-e9d5-415e-bae9-3146329ed9e6 -> Lung Opacity
Processing 259/30227: 065b3a2f-1af3-4ebd-a740-9e49f9c685db -> No Lung Opacity
Processing 260/30227: 065b79b6-9a76-4b92-9417-de09b3d97cd5 -> No Lung Opacity
Processing 261/30227: 06605bfa-0370-4979-a2bd-11173002abd1 -> Normal
Processing 262/30227: 06634f15-9c78-47a1-97eb-f10f4c210765 -> Lung Opacity
Processing 263/30227: 06634f15-9c78-47a1-97eb-f10f4c210765 -> Lung Opacity
Processing 264/30227: 0666201a-fab4-4828-81dd-73292312c766 -> Normal
Processing 265/30227: 06697be9-b1ab-444c-af0d-fd11a053f2b3 -> Lung Opacity
Processing 266/30227: 06697be9-b1ab-444c-af0d-fd11a053f2b3 -> Lung Opacity
Processing 267/30227: 066d9e27-e48f-4453-b1e1-d73c34910722 -> Lung Opacity
Processing 268/30227: 066e0d5c-0f47-425c-aa7f-9003c355086b -> No Lung Opacity
Processing 269/30227: 06737bed-8dc1-47d9-8c30-324282dcc84d -> Lung Opacity

In [1]:
import os
import pydicom
import numpy as np
import cv2

input_dir = "D:\Project\AI That Explains Medical Images Like a Doctor\Another way\Dataset\stage_2_test_images"
output_dir = "images/test"
os.makedirs(output_dir, exist_ok=True)
i=0
for file in os.listdir(input_dir):
    if file.endswith(".dcm"):
        i+=1
        print(f"Processing file {i}: {file}")     
        path = os.path.join(input_dir, file)
        ds = pydicom.dcmread(path)

        image = ds.pixel_array.astype(np.float32)
        image = (image - image.min()) / (image.max() - image.min())
        image = (image * 255).astype(np.uint8)

        out_path = os.path.join(output_dir, file.replace(".dcm", ".png"))
        cv2.imwrite(out_path, image)

print("All DICOM files converted!")

Processing file 1: 0000a175-0e68-4ca4-b1af-167204a7e0bc.dcm
Processing file 2: 0005d3cc-3c3f-40b9-93c3-46231c3eb813.dcm
Processing file 3: 000686d7-f4fc-448d-97a0-44fa9c5d3aa6.dcm
Processing file 4: 000e3a7d-c0ca-4349-bb26-5af2d8993c3d.dcm
Processing file 5: 00100a24-854d-423d-a092-edcf6179e061.dcm
Processing file 6: 0015597f-2d69-4bc7-b642-5b5e01534676.dcm
Processing file 7: 001b0c51-c7b3-45c1-9c17-fa7594cab96e.dcm
Processing file 8: 0022bb50-bf6c-4185-843e-403a9cc1ea80.dcm
Processing file 9: 00271e8e-aea8-4f0a-8a34-3025831f1079.dcm
Processing file 10: 0028450f-5b8e-4695-9416-8340b6f686b0.dcm
Processing file 11: 002bcde0-d8da-4931-ab04-5d724e30261b.dcm
Processing file 12: 002fcb77-ef76-4626-ab34-5070f15c20db.dcm
Processing file 13: 003206b4-bd4a-4684-8d49-76f4cb713a30.dcm
Processing file 14: 00330f7f-d114-4eb2-9c6e-558eeb3084a1.dcm
Processing file 15: 00342ae8-ff81-4229-adf6-6a2ab711707b.dcm
Processing file 16: 003d17f0-bd8a-485c-bc8b-daec33f53efa.dcm
Processing file 17: 003dba79-1b1d-4713-add8-d72c54074f8a.dcm
Processing file 18: 003ec9e3-512e-4f6e-923d-daa9f9f3db9a.dcm
Processing file 19: 003fbda2-ba55-4714-a03a-83f15bec19e4.dcm
Processing file 20: 0041fc67-793c-4129-a952-ea3fb821b445.dcm
Processing file 21: 00475531-1036-4ab4-8c12-1eac7e9ddfd1.dcm
Processing file 22: 0048e89e-f88a-41a1-b79f-ab4e7135627e.dcm
Processing file 23: 004b28ac-d188-427b-8a21-10501125f596.dcm
Processing file 24: 004f0a0f-fb54-4068-8b67-d3eef6724f44.dcm
Processing file 25: 004f720d-482c-4982-b866-1a327e51eaba.dcm
Processing file 26: 0050f8bb-36a4-4a1a-8de5-2d73154c2571.dcm
Processing file 27: 0051fc13-694d-43d4-bbca-5a185f90418f.dcm
Processing file 28: 00525b72-7c03-4328-9c02-6393704810d8.dcm
Processing file 29: 006081fc-cd84-4675-828a-784d2521fcc7.dcm
Processing file 30: 00632296-ea6d-438e-982d-370b771a6059.dcm
Processing file 31: 0066ba32-08b6-4ac9-8d5a-abec69825d53.dcm
Processing file 32: 00679577-c370-4aff-ab2b-fc4846c3eabb.dcm
Processing file 33: 0068492c-2cc4-46b3-9ac5-ccb80fc10c96.dcm
Processing file 34: 006be30e-1295-4053-9ffc-fab6b527e7d9.dcm
Processing file 35: 00722cea-8cb4-488c-91a1-402d3cfab7a3.dcm
Processing file 36: 00748fc6-3e87-482a-a0b4-ca2b0a7686a3.dcm
Processing file 37: 00763ba7-af28-4893-a403-08490fcdd69c.dcm
Processing file 38: 0076e39f-5189-4751-8274-da6df4d5e429.dcm
Processing file 39: 0076e68b-90cf-45da-a839-e67d3131182b.dcm
Processing file 40: 00786b27-31a0-4aeb-8513-9528fffe7b87.dcm
Processing file 41: 007d9048-a1f4-49ea-8fb1-f228dc4b6cda.dcm
Processing file 42: 007f06ce-348d-421c-968b-8b35ccb3487c.dcm
Processing file 43: 008102ab-5ea6-414d-bff1-9f55d148a80d.dcm
Processing file 44: 00860e86-5b18-4694-a20a-0b47e842a453.dcm
Processing file 45: 0086a7a6-c663-401a-a908-378e87ebe45a.dcm
Processing file 46: 008ca187-f164-4a2b-b14e-29d4e16e3a66.dcm
Processing file 47: 008efe9c-946b-4f43-ae07-942f8d73dcc1.dcm
Processing file 48: 0092f442-ccb5-49a2-81cf-b6ca3f829a53.dcm
Processing file 49: 0094bcae-2cdd-48ca-9630-7d4157f78415.dcm
Processing file 50: 0094c2b8-5da2-4e25-a177-b4eea16bd671.dcm
Processing file 51: 00991acc-85b3-41c7-a397-bdf925c3697a.dcm
Processing file 52: 009ac78b-6b5c-45ef-b73b-855116887af4.dcm
Processing file 53: 009c7a22-8272-4acd-a1ee-03de8d420b11.dcm
Processing file 54: 00a221ac-da8f-4f61-8d4f-fc195143491d.dcm
Processing file 55: 00ad18b7-06ee-4c4d-abca-14bdf814e8b2.dcm
Processing file 56: 00af3668-1970-4f65-a292-525d2c5aed5c.dcm
Processing file 57: 00b4ac1b-fa09-4dbe-b93f-7d9e52992a68.dcm
Processing file 58: 00b4e593-fcf8-488c-ae55-751034e26f16.dcm
Processing file 59: 00b9585a-9825-4892-8829-ddd75218bd1a.dcm
Processing file 60: 00c0f4e4-ac8b-4dea-8231-802f6b9860dc.dcm
Processing file 61: 00c67fbc-35f6-4058-88b4-4bfad19014ec.dcm
Processing file 62: 00ca48ec-39b3-4650-80ed-1fab342aba0e.dcm
Processing file 63: 00d61d6f-d150-46e1-bab7-0a7a36a0cc80.dcm
Processing file 64: 00dddf53-486f-4098-9a5e-b7d0b8ee2b8f.dcm
Processing file 65: 00dec011-0053-493a-9c51-3fc3524b3357.dcm
Processing file 66: 00e42241-12a0-490a-b856-db3e4ab41104.dcm
Processing file 67: 00edcd2d-d727-486d-b15a-675855e4dca3.dcm
Processing file 68: 00f376d8-24a0-45b4-a2fa-fef47e2f9f9e.dcm
Processing file 69: 00f3a73b-1801-43f7-992d-38338ec58a90.dcm
Processing file 70: 00fde673-62b3-4a5c-9b9a-6c1ec8f66910.dcm
Processing file 71: 00fe1990-071e-4f90-b8c5-08fc94ff40e3.dcm
Processing file 72: 010355fd-a8c0-4503-993e-16412a3b8136.dcm
Processing file 73: 01036427-2c3e-4a79-b472-2c7bca1efa86.dcm
Processing file 74: 0105b36d-2d7c-4431-9b5b-fa6acb31ee1d.dcm
Processing file 75: 0106724a-2379-4897-8504-dfaa6db072de.dcm
Processing file 76: 0107394f-5672-4969-8a15-279714669f63.dcm
Processing file 77: 010763a7-7394-49da-8fe2-6588a805062a.dcm
Processing file 78: 0107871b-1095-4cd5-a197-bc7715873cbf.dcm
Processing file 79: 0107acc8-bddd-4889-a18a-c54449c6844a.dcm
Processing file 80: 010be344-5412-4cc8-afab-fb07f29e3356.dcm
Processing file 81: 010d5095-acc6-4210-8753-eea1b0734a76.dcm
Processing file 82: 010f1670-a3f9-4186-b54f-720e3a78b9fd.dcm
Processing file 83: 0110317f-73a0-43db-aace-49f4aabd781f.dcm
Processing file 84: 0110a566-f774-4554-bdda-a1883ebd2f5c.dcm
Processing file 85: 01119341-8004-44c4-9537-0e47c4b67689.dcm
Processing file 86: 01137316-5474-4e6e-ad95-46e50916da83.dcm
Processing file 87: 0114657d-6647-492a-9494-110ba43e4135.dcm
Processing file 88: 011775bb-cb07-4a6e-ab91-d40c4dbd5c56.dcm
Processing file 89: 0118519d-7a19-4ad2-b5a5-5265cb86cb2a.dcm
Processing file 90: 011949a0-b52b-424d-b78f-afc3926ef2de.dcm
Processing file 91: 011b475b-4b74-4857-8221-d15d71ba64a9.dcm
Processing file 92: 011d6083-abaa-4b28-8a53-36aa0cddb3b5.dcm
Processing file 93: 011df306-5ca7-442e-bd54-f05820d84396.dcm
Processing file 94: 01200366-f4e5-46c2-8b1d-1d27075231ce.dcm
Processing file 95: 0123ddde-aa60-4364-a3c5-2aed75bba3dd.dcm
Processing file 96: 012469b7-1b4b-4407-8c1b-7236861d49a3.dcm
Processing file 97: 0124f347-a386-462e-ac00-4b3ddb2ed159.dcm
Processing file 98: 012d2cf2-f973-4bf1-934f-295df6e44b60.dcm
Processing file 99: 012e4288-deac-438d-af9e-a3cb7478ed7f.dcm
Processing file 100: 012f2ccc-8ac8-4cc0-9da1-a282db470d12.dcm
Processing file 101: 0133a3a9-350d-4501-a59f-6a7e74fbc1c8.dcm
Processing file 102: 0133cd26-6796-48d3-a092-adae7ce07d61.dcm
Processing file 103: 013c572e-c377-431e-a4b8-34f22f2f8a30.dcm
Processing file 104: 0140cefe-d9c1-4de5-a59b-1aad98e4b62a.dcm
Processing file 105: 0143f05b-f5f5-4147-a9e3-7f525e45a2ce.dcm
Processing file 106: 014647d1-a977-4bfe-9f35-869b168ea0fb.dcm
Processing file 107: 0146516d-b739-4103-8cc6-bb2b494e1d5b.dcm
Processing file 108: 01478a83-71ad-4319-83b8-d0093bd22dfb.dcm
Processing file 109: 0147a753-be33-4c13-8cd7-9cee88fffcf6.dcm
Processing file 110: 014a7eee-8245-479b-87a9-a9402c66502b.dcm
Processing file 111: 014ae099-4762-46d3-a3b9-7fd25e3337c0.dcm
Processing file 112: 014f2256-b71e-4168-84f7-bac69852057e.dcm
Processing file 113: 01512575-81f5-4de3-9645-1bf3050dced8.dcm
Processing file 114: 01528f70-440c-41fc-8673-e3ae6464380b.dcm
Processing file 115: 01594bc6-16eb-4214-b2b2-4cf2154dbab9.dcm
Processing file 116: 015a202d-5e18-4dcf-802c-0f7e75e14a38.dcm
Processing file 117: 0165543b-85d3-4dd2-9e93-6c5ab10f13da.dcm
Processing file 118: 01671e79-a1a5-46a8-bbe5-dd8e514f7923.dcm
Processing file 119: 016d6d63-e32a-4df0-ad43-e42f808ab480.dcm
Processing file 120: 016fe150-be99-4c53-96a3-ee0eeec4a62a.dcm
Processing file 121: 01708093-89aa-40aa-a121-4c8011fd0016.dcm
Processing file 122: 0175314a-05e7-4ada-9f27-7b874f29842a.dcm
Processing file 123: 01767b2b-8915-47ee-9bb8-3511492f7df5.dcm
Processing file 124: 01789dfc-da09-4460-8326-32c143e767be.dcm
Processing file 125: 017a4e3a-191b-4013-a228-dabb749a3d70.dcm
Processing file 126: 017cebf7-65c6-4508-bf78-14eb93001ab7.dcm
Processing file 127: 0181dc21-34be-4d57-87d9-74d91afc2458.dcm
Processing file 128: 01833e4e-6d0a-4ea5-bc98-638a70a66e50.dcm
Processing file 129: 018b01e1-7582-4141-949d-0c53d8f6806e.dcm
Processing file 130: 018cb7c3-0ec3-484d-a6a3-bd7c376605d1.dcm
Processing file 131: 01960630-c20f-412b-b5c6-9ab2e06d64a3.dcm
Processing file 132: 0196bb90-2e5a-401b-bffb-7fd7258d6844.dcm
Processing file 133: 01972669-8b42-4b47-96ac-e6a085e504ba.dcm
Processing file 134: 0198e5bc-ea34-4e84-b21f-1a3ea96801ab.dcm
Processing file 135: 019a58b2-6b0c-42d8-948d-b9fcc3d47eb8.dcm
Processing file 136: 019a638a-305f-422d-aec7-f1081f510046.dcm
Processing file 137: 019bf13a-7fd5-417a-8959-ba79e9b9f875.dcm
Processing file 138: 020d940f-e100-4c82-8f44-58174dc28684.dcm
Processing file 139: 02186c9c-2598-4b9f-9752-b0c9e7c9128c.dcm
Processing file 140: 021ca4f1-52fd-4881-85cf-c57dfa74566b.dcm
Processing file 141: 021d0bd9-560c-43de-80de-5efa191f3251.dcm
Processing file 142: 021fe6f6-dc70-463a-a2fa-bff41f74af6a.dcm
Processing file 143: 02256e17-eef9-412c-a03c-39e2eb2e6392.dcm
Processing file 144: 02270587-8e6d-4799-b689-a161db7c5c91.dcm
Processing file 145: 022a1092-db63-4f8c-a7fe-77019dd4c52e.dcm
Processing file 146: 022eeb32-8192-44f5-ae9b-1e20ba387890.dcm
Processing file 147: 02305324-c307-4811-8932-6831366047d1.dcm
Processing file 148: 0232e608-a7af-4af7-a104-32537c1cb26b.dcm
Processing file 149: 02347c05-a319-41a9-88b4-59ef119221b3.dcm
Processing file 150: 02431455-505f-4ece-bac3-b4f494c65366.dcm
Processing file 151: 02462e7b-800c-4b19-904b-0a1fb80f4fc4.dcm
Processing file 152: 0246ec39-4938-4c8f-bfb6-c750d0313ee4.dcm
Processing file 153: 02500219-bcb2-462d-8c02-857a53a2f969.dcm
Processing file 154: 025375ff-f79d-42ab-a443-b0d5671eaffc.dcm
Processing file 155: 0254cbc4-8fb8-4e07-8bc6-430d337e66a7.dcm
Processing file 156: 0255119f-2fcb-40dd-8e89-5da9a6318e47.dcm
Processing file 157: 025d7915-74a1-4d0e-83b7-d2cfc1e1ac54.dcm
Processing file 158: 025fd656-c29a-478b-a2f2-cf68a38faee9.dcm
Processing file 159: 02693444-dc0d-4ac0-8cd0-cbaed1844da3.dcm
Processing file 160: 02697c06-6d28-49ec-a66e-2eeafeb19358.dcm
Processing file 161: 0270091f-28e0-4bdd-bb52-26e26bdf9f66.dcm
Processing file 162: 02718efb-79db-40cc-9f03-4c0a667f3ee5.dcm
Processing file 163: 02724047-234e-43ea-8418-62ab74f05668.dcm
Processing file 164: 027301a0-cb61-4431-8736-503d0c23cd48.dcm
Processing file 165: 02780306-5d72-4377-8183-37c3e0e13e55.dcm
Processing file 166: 027a5fac-783a-4dd8-b032-06a8b8d05546.dcm
Processing file 167: 0280af91-28aa-44ae-b693-c091db206244.dcm
Processing file 168: 028b7794-c17e-4bef-ba97-3b9523bc1333.dcm
Processing file 169: 028fad21-f2a0-4778-8ad2-fcee826331d0.dcm
Processing file 170: 02952fe2-ceab-4e55-b1af-71f40a209a1f.dcm
Processing file 171: 029760af-1273-42c5-a214-0267fbe016fe.dcm
Processing file 172: 0298e825-f153-4c95-a244-e24060d28bc2.dcm
Processing file 173: 02a378a0-0229-4f11-9a1c-bf32332645da.dcm
Processing file 174: 02a54bea-8b9b-4572-9f7b-bccda112e6b8.dcm
Processing file 175: 02ae356b-c39e-474f-908f-0af600e6b03d.dcm
Processing file 176: 02ae4bbd-7dfa-489d-9bbd-e43e60ff876e.dcm
Processing file 177: 02b42e7e-d0da-43b7-9a54-458264099d08.dcm
Processing file 178: 02b7bd21-0ca3-48b0-b98c-dd85a7ad1c0f.dcm
Processing file 179: 02b7f2f0-b8e0-41c8-9cfc-83c69d202c67.dcm
Processing file 180: 02bc74a8-2ea2-4d73-a7b4-d2ae9c1ddfd7.dcm
Processing file 181: 02c19fee-bf32-4969-8ba4-7e996f1f9f3a.dcm
Processing file 182: 02c3e45e-a066-4f4d-9dfe-c21c30df579b.dcm
Processing file 183: 02c43b6e-b603-4d06-b579-3287b7eed859.dcm
Processing file 184: 02d0f144-bcc1-4258-bbf7-aa2bb3408ecc.dcm
Processing file 185: 02d4d116-415d-49cb-91bc-98b97c973ad3.dcm
Processing file 186: 02d6943e-66b0-4d0f-80ef-a468e937b663.dcm
Processing file 187: 02d8eb87-93ea-4e76-94fe-2fce14a93c6c.dcm
Processing file 188: 02d9c45e-5f0c-4823-90af-51ff9e81ad40.dcm
Processing file 189: 02eaa8c2-e818-4b39-92d3-aa092553b811.dcm
Processing file 190: 02ed876f-f335-482d-af13-0d0b8af51774.dcm
Processing file 191: 02ee9955-1ae1-4c2c-86ca-5c8ff8d56d4c.dcm
Processing file 192: 02eead22-409f-4d50-ae60-e8996493a111.dcm
Processing file 193: 02eff1f9-5830-4e4f-a68e-822ac02047f7.dcm
Processing file 194: 02f29ed2-889c-4766-8e4e-853d8f71a12c.dcm
Processing file 195: 02fcdbb1-2ff5-41bb-a28f-a0e5d9a83d51.dcm
Processing file 196: 0300003e-3405-43a3-b5d9-d314d4810fdb.dcm
Processing file 197: 03055987-3303-429f-8979-cecf701707e5.dcm
Processing file 198: 0305bbcb-4998-4020-9a9f-b32f448e30bf.dcm
Processing file 199: 030cf802-d118-431e-ba63-43726072a919.dcm
Processing file 200: 0310b580-0ba0-4b74-9de2-db046feddaec.dcm
Processing file 201: 03161440-f3b4-408e-bcac-c902b47f1166.dcm
Processing file 202: 0316721f-901b-4828-a1ed-c7ab71a0141d.dcm
Processing file 203: 03188698-bad7-46f7-94d3-5487b2c67b8a.dcm
Processing file 204: 03190b26-7d61-4cbc-abcb-bba18884254d.dcm
Processing file 205: 0319220c-e0ec-4262-bafd-c5d650ff5e69.dcm
Processing file 206: 031b6254-ded2-423a-947a-c4018797c544.dcm
Processing file 207: 031cc0e4-9e42-4bfe-9d0c-fb3170cfdc2f.dcm
Processing file 208: 031eb51e-fec5-4b16-9bfd-2c6a49b2f34b.dcm
Processing file 209: 0320cae5-82c5-460e-96f8-754354697b8e.dcm
Processing file 210: 03226a3c-7341-479d-8188-ebd0e52593a7.dcm
Processing file 211: 0322a3ad-3e24-4e6d-8f24-b68e3c61d88f.dcm
Processing file 212: 032463f7-34e0-4bf3-906a-09e5e2956882.dcm
Processing file 213: 032b9367-1ce3-44e8-9b74-8f3e2203e8ec.dcm
Processing file 214: 032bb477-dc70-491e-94f3-0ee5c8d43fb2.dcm
Processing file 215: 032d8361-e8b5-4e8a-905a-9fae58f42398.dcm
Processing file 216: 032f8386-fd1d-4ffd-b12a-263a4ce113ae.dcm
Processing file 217: 0332bce4-6181-48a5-ac40-b426f50abcc4.dcm
Processing file 218: 0336175b-db12-4592-806a-51a3ce54e5bf.dcm
Processing file 219: 03367507-9db5-496d-a20f-bc161f097d51.dcm
Processing file 220: 033af663-f044-43ab-a569-298cc4bf37bc.dcm
Processing file 221: 0340ffe8-feef-4b08-a1fa-328bb093361c.dcm
Processing file 222: 0343df14-527e-4f73-9a56-3fef4b0104de.dcm
Processing file 223: 0346fcf4-68e1-4027-b0e7-67b3d53f54b0.dcm
Processing file 224: 034ac9cb-fdc9-4e20-b39c-f4d9eaf8df91.dcm
Processing file 225: 034bda9f-cd72-457e-8dfc-e7ca6634fabe.dcm
Processing file 226: 034c963e-7d6e-4350-b2ff-8e534ccf562d.dcm
Processing file 227: 034e373b-aa5d-4464-8528-a280a42bc651.dcm
Processing file 228: 034e908e-6cef-4ecb-82b3-d9c8a243a60e.dcm
Processing file 229: 03549d12-0dd8-4a61-ba7c-ecb4afe06200.dcm
Processing file 230: 0357ec4c-be16-4c0c-a0e9-7fa38df30c84.dcm
Processing file 231: 0358c757-07f5-4114-a1d6-d37b7aa9eb77.dcm
Processing file 232: 035a2dce-5d55-401c-9038-3fc93f291a97.dcm
Processing file 233: 035c8891-656e-4422-82a0-a53406dae9ba.dcm
Processing file 234: 035f53cc-065d-417b-85b4-b4a5a7243758.dcm
Processing file 235: 0360a37c-7f05-4809-a645-db5c0e790145.dcm
Processing file 236: 03627000-edeb-4f01-927a-50662d0deab8.dcm
Processing file 237: 03675081-3f27-4e22-a1dd-6cccd8c4cc92.dcm
Processing file 238: 036a4964-81d7-4d80-8511-5ad2d77f479e.dcm
Processing file 239: 0371b8f9-9f18-4f4c-9c9c-38867e373437.dcm
Processing file 240: 03727d3c-2f77-4bd8-ae6f-002b30fda71c.dcm
Processing file 241: 03772765-8195-404c-8bba-fd6dd5563213.dcm
Processing file 242: 0377791b-ae5b-4abb-b6ae-ac8582ac6f33.dcm
Processing file 243: 037876f4-0e2d-45c6-8e98-b1cac93b9066.dcm
Processing file 244: 037baafe-07de-49e7-ae6b-2fac90640f0b.dcm
Processing file 245: 037d1b26-3dc7-48c2-b93c-214e7538c76d.dcm
Processing file 246: 037ed56b-77ae-4084-a0d3-26be1d8a46dd.dcm
Processing file 247: 037eff4a-1840-47bf-92d3-98898b91165d.dcm
Processing file 248: 037f16ff-46b6-45bf-b737-74072c46fab7.dcm
Processing file 249: 037ffaa8-d381-41af-b14e-a95b2d4b347a.dcm
Processing file 250: 03800681-c722-448f-bf8c-635080a95f00.dcm
Processing file 251: 0382a252-b1b3-477d-bf8f-15da22a7f19c.dcm
Processing file 252: 03858c3a-5c32-4503-8888-58f2f601c1df.dcm
Processing file 253: 0385be2c-896e-489d-8b09-bac5694ce5ed.dcm
Processing file 254: 0385d49e-7642-445a-bffc-28915cee0056.dcm
Processing file 255: 03866050-4736-47c1-ab69-d084d6561b9e.dcm
Processing file 256: 0389a598-b5f0-43a5-9a98-7dfdd08e0b9f.dcm
Processing file 257: 038cd87f-d57f-4db6-9548-879dc697d656.dcm
Processing file 258: 03900c12-0a25-4a24-a3b6-38992cd7e050.dcm
Processing file 259: 03a37eda-cff4-4ad9-b5d7-5f9ab9dbbfe3.dcm
Processing file 260: 03a4ba96-d15e-4fb0-bcc5-a2987916786a.dcm
Processing file 261: 03a75f93-bdfb-4e5a-89f3-548b04fdbb5e.dcm
Processing file 262: 03ae3399-3ca3-4e4e-bf4e-5e5d57dc20e3.dcm
Processing file 263: 03ae4a8a-0f24-4de4-a791-665db68a2f2c.dcm
Processing file 264: 03b045bf-4b5e-4530-817d-64c5973a57c4.dcm
Processing file 265: 03b16b8f-a03c-409c-8740-7e694b7d58e5.dcm
Processing file 266: 03bbf8a4-f4a1-46a0-a64a-6613d875f80b.dcm
Processing file 267: 03bc0c5f-af69-4a4a-8f4e-e1301e0f9a4e.dcm
Processing file 268: 03bc2ba2-2617-4c8b-a0fe-81b0a915d066.dcm
Processing file 269: 03bc6e8d-73df-432c-92be-9f6fe2eb7e34.dcm
Processing file 270: 03beea3b-3d59-4f8d-a5f8-a02ae3bda6a2.dcm
Processing file 271: 03c86a26-4053-4e4f-8e3e-6229cb4c4881.dcm
Processing file 272: 03c9f53b-f5f8-4c9f-b69c-0986ab3fec68.dcm
Processing file 273: 03cc6b7a-4eef-46e3-98e0-fe3990325b36.dcm
Processing file 274: 03d837fb-4528-4e56-bf4e-58fbeae187bb.dcm
Processing file 275: 03dbe705-0a6c-434d-9b6c-93d7f2f76429.dcm
Processing file 276: 03dfd775-0cb4-4ede-9eba-e01df8a84965.dcm
Processing file 277: 03e146ff-fd62-4188-9ffa-c61b8f89ac8d.dcm
Processing file 278: 03e73ec7-8b85-49d3-9740-d6151fcc32f8.dcm
Processing file 279: 03f24805-e3c3-4943-ba67-a9bcb43a2533.dcm
Processing file 280: 03f95b1e-3378-4ccc-aa69-fdb7dd4d988a.dcm
Processing file 281: 03f9e13f-1239-4d82-802d-3ea20731e1db.dcm
Processing file 282: 03f9f71c-8f7f-47c1-b39a-14fbd3d30c98.dcm
Processing file 283: 03fc4207-b6f6-4c97-8d55-8f624ea91c50.dcm
Processing file 284: 03fcfa7a-8d70-437a-ad1e-7172023cbdeb.dcm
Processing file 285: 03fe8276-9e0a-4f77-816e-e0991f3b7dfb.dcm
Processing file 286: 03ff2e8b-e8c6-4a63-a426-f06c9a76d1ac.dcm
Processing file 287: 04026d9e-895d-4b87-9d73-3d6fb58e53a3.dcm
Processing file 288: 040cfecb-0984-4393-a977-924c75795809.dcm
Processing file 289: 04170f9f-5d56-4ef7-9960-0afe2b50f778.dcm
Processing file 290: 04176263-de7f-471b-9dc1-7a5af4e6d943.dcm
Processing file 291: 0417f292-9baa-47d3-a4a6-9cab52844cec.dcm
Processing file 292: 041a2204-51fb-4d23-8204-dd6a7a6f5ee3.dcm
Processing file 293: 041b4ab2-82e4-48a0-a8b1-4993144f212b.dcm
Processing file 294: 04269ea9-d43c-4f01-a72a-d340fb49ff27.dcm
Processing file 295: 04273d76-c04b-44e0-b9bf-561e30c837f0.dcm
Processing file 296: 0428151f-e4fe-436c-bc09-12e3bd84f4df.dcm
Processing file 297: 0428a988-106d-4ce8-a67b-2ee1827a825a.dcm
Processing file 298: 042d37c9-b83f-40f6-8d8e-85022c7f3a14.dcm
Processing file 299: 0431b96a-9e84-4d8b-8e9c-b28c91e10f4a.dcm
Processing file 300: 043711b3-ff14-463a-b38a-6f8e2d0b1a9a.dcm
Processing file 301: 04384b80-0b9e-4744-85e4-f5184fc073e9.dcm
Processing file 302: 043d020e-c61b-40ac-8704-be5ed7ded293.dcm
Processing file 303: 043f1056-2a3c-4301-864c-6b2720350496.dcm
Processing file 304: 04420ae7-2c04-4c42-a0a9-58f12e211a50.dcm
Processing file 305: 0444a749-4fde-46be-8202-bc2ddb71d5d9.dcm
Processing file 306: 0444d942-dc61-46ed-b4a8-422f15b74087.dcm
Processing file 307: 044702b8-5ad7-493c-ac3b-1fe5292a62b2.dcm
Processing file 308: 04514c74-98f2-4f73-b39f-869e762dbb6d.dcm
Processing file 309: 0452d6c6-4693-4ade-8b20-46e09c719ada.dcm
Processing file 310: 04596200-fe71-4b08-8184-431a24a6c8b2.dcm
Processing file 311: 0459da81-0980-4cc7-82fb-4f50975cb52d.dcm
Processing file 312: 045d09ff-cc44-4c5f-952f-b83373bb2d93.dcm
Processing file 313: 045e5500-3dcc-4d9b-8dc2-a85c611dd497.dcm
Processing file 314: 045fad52-8652-4827-b725-cb616b4c482c.dcm
Processing file 315: 045fe561-d85a-4a9e-b0c4-9733f30305c7.dcm
Processing file 316: 04603933-3d07-4725-9d50-f4ff2302d7df.dcm
Processing file 317: 0460484c-d06c-4156-8690-89124ab751e8.dcm
Processing file 318: 0460e5b6-4298-419e-a930-d9aab8c4f271.dcm
Processing file 319: 04627a72-3f26-4b2e-864a-01da3abc0cee.dcm
Processing file 320: 04644a8f-bd70-484a-a4db-7ea330c6177c.dcm
Processing file 321: 0466a624-c075-4db1-9e03-f58d09bc27ff.dcm
Processing file 322: 0467d282-4548-4430-bc98-1c3dbfc96e8c.dcm
Processing file 323: 046a9f1a-abb6-4e75-94f5-a98a197a3ee9.dcm
Processing file 324: 046d7152-9614-49b3-8883-ebb9d3782205.dcm